### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by AleDss1374** [muki01/Windows-Activator#1]
Scanned with virustotal out of suspition. I guess I'm lucky I did...

https://www.virustotal.com/gui/file/2a66f9a30e3068c0b45fc38412a60f8728c062df9337e69de1f84ceabbd30260/summary

**Comment by muki01** [comment]
The .exe file shows up as a virus because of my Bat to Exe converter. The converter probably adds some scripts to convert it to .exe file. You can use the .cmd file there, it won't be considered a virus.
